CREATE TABLE [dbo].[CONTRAT] (
  [NUM_DE_CONTRAT] [char](32) NOT NULL,
  [MATRICULE_SRL] [smallint] NOT NULL,
  [TYPE_DE_CONTRAT] [text] NOT NULL,
  [SALAIRE_DE_BASE] [money] NOT NULL,
  [DATE_D_EMBAUCH] [datetime] NOT NULL,
  [DATE_FIN_DE_CONTRAT] [datetime] NOT NULL,
  CONSTRAINT [PK_CONTRAT] PRIMARY KEY CLUSTERED ([NUM_DE_CONTRAT])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTRAT]
  ADD CONSTRAINT [FK_CONTRAT_SALARIE] FOREIGN KEY ([MATRICULE_SRL]) REFERENCES [dbo].[SALARIE] ([MATRICULE_SRL])
GO