CREATE TABLE [dbo].[SCP] (
  [MATRICULE_SRL] [smallint] NOT NULL,
  [CODE_COT_PRS] [char](32) NOT NULL,
  CONSTRAINT [PK_SCP] PRIMARY KEY CLUSTERED ([MATRICULE_SRL], [CODE_COT_PRS])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCP]
  ADD CONSTRAINT [FK_SCP_COTISATION_PERSONNEL] FOREIGN KEY ([CODE_COT_PRS]) REFERENCES [dbo].[COTISATION_PERSONNEL] ([CODE_COT_PRS])
GO

ALTER TABLE [dbo].[SCP]
  ADD CONSTRAINT [FK_SCP_SALARIE] FOREIGN KEY ([MATRICULE_SRL]) REFERENCES [dbo].[SALARIE] ([MATRICULE_SRL])
GO