CREATE TABLE [dbo].[BULLETIN] (
  [N_BLT] [char](32) NOT NULL,
  [MATRICULE_SRL] [smallint] NOT NULL,
  [DATE_DEBUT_PER] [datetime] NOT NULL,
  [DATE_FIN_PER] [datetime] NOT NULL,
  CONSTRAINT [PK_BULLETIN] PRIMARY KEY CLUSTERED ([N_BLT])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[BULLETIN]
  ADD CONSTRAINT [FK_BULLETIN_SALARIE] FOREIGN KEY ([MATRICULE_SRL]) REFERENCES [dbo].[SALARIE] ([MATRICULE_SRL])
GO