CREATE TABLE [dbo].[AVANCE] (
  [CODE_AVC] [char](32) NOT NULL,
  [MATRICULE_SRL] [smallint] NOT NULL,
  [DATE_AVC] [datetime] NOT NULL,
  [AVANCE] [money] NOT NULL,
  CONSTRAINT [PK_AVANCE] PRIMARY KEY CLUSTERED ([CODE_AVC])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[AVANCE]
  ADD CONSTRAINT [FK_AVANCE_SALARIE] FOREIGN KEY ([MATRICULE_SRL]) REFERENCES [dbo].[SALARIE] ([MATRICULE_SRL])
GO