CREATE TABLE [dbo].[SALARIE] (
  [MATRICULE_SRL] [smallint] NOT NULL,
  [NOM_SRL] [text] NOT NULL,
  [PRENOM_SRL] [text] NOT NULL,
  [DATE_D_EMBAUCHE] [datetime] NOT NULL,
  [SALAIRE_DE_BASE] [money] NOT NULL,
  [SITUATION_FAMILIALE] [text] NOT NULL,
  [NBR_D_ENFANT] [smallint] NOT NULL,
  [CIN_SRL] [char](32) NOT NULL,
  [ADRESSE_SRL] [char](32) NOT NULL,
  [EMAIL_SRL] [char](32) NOT NULL,
  [TEL_SRL] [smallint] NOT NULL,
  [SEXE_SRL] [text] NOT NULL,
  [CODE_POST_SRL] [smallint] NOT NULL,
  [VILLE_SRL] [text] NOT NULL,
  CONSTRAINT [PK_SALARIE] PRIMARY KEY CLUSTERED ([MATRICULE_SRL])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO