CREATE TABLE [dbo].[SI] (
  [MATRICULE_SRL] [smallint] NOT NULL,
  [CODE_IDM] [char](32) NOT NULL,
  CONSTRAINT [PK_SI] PRIMARY KEY CLUSTERED ([MATRICULE_SRL], [CODE_IDM])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SI]
  ADD CONSTRAINT [FK_SI_INDEMNITES] FOREIGN KEY ([CODE_IDM]) REFERENCES [dbo].[INDEMNITES] ([CODE_IDM])
GO

ALTER TABLE [dbo].[SI]
  ADD CONSTRAINT [FK_SI_SALARIE] FOREIGN KEY ([MATRICULE_SRL]) REFERENCES [dbo].[SALARIE] ([MATRICULE_SRL])
GO