CREATE TABLE [dbo].[SCF] (
  [MATRICULE_SRL] [smallint] NOT NULL,
  [CODE_COT_FIS] [char](32) NOT NULL,
  CONSTRAINT [PK_SCF] PRIMARY KEY CLUSTERED ([MATRICULE_SRL], [CODE_COT_FIS])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCF]
  ADD CONSTRAINT [FK_SCF_COTISATION_FISCALE] FOREIGN KEY ([CODE_COT_FIS]) REFERENCES [dbo].[COTISATION_FISCALE] ([CODE_COT_FIS])
GO

ALTER TABLE [dbo].[SCF]
  ADD CONSTRAINT [FK_SCF_SALARIE] FOREIGN KEY ([MATRICULE_SRL]) REFERENCES [dbo].[SALARIE] ([MATRICULE_SRL])
GO