CREATE TABLE [dbo].[PRET] (
  [CODE_PRET] [char](32) NOT NULL,
  [DATE_DE_PRET] [datetime] NOT NULL,
  [MNT_PRET] [money] NOT NULL,
  [PRD_PRET] [real] NOT NULL,
  CONSTRAINT [PK_PRET] PRIMARY KEY CLUSTERED ([CODE_PRET])
)
ON [PRIMARY]
GO