CREATE TABLE [dbo].[SCS] (
  [MATRICULE_SRL] [smallint] NOT NULL,
  [CODE_COT_SOC] [char](32) NOT NULL,
  CONSTRAINT [PK_SCS] PRIMARY KEY CLUSTERED ([MATRICULE_SRL], [CODE_COT_SOC])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCS]
  ADD CONSTRAINT [FK_SCS_COTISATION_SOCIALE] FOREIGN KEY ([CODE_COT_SOC]) REFERENCES [dbo].[COTISATION_SOCIALE] ([CODE_COT_SOC])
GO

ALTER TABLE [dbo].[SCS]
  ADD CONSTRAINT [FK_SCS_SALARIE] FOREIGN KEY ([MATRICULE_SRL]) REFERENCES [dbo].[SALARIE] ([MATRICULE_SRL])
GO