CREATE TABLE [dbo].[CONTRAT] (
  [NUMCONTRAT] [char](32) NOT NULL,
  [MATRICULE] [smallint] NOT NULL,
  [TYPECONTRAT] [text] NOT NULL,
  [SALAIRE_DE_BASE] [money] NOT NULL,
  [DATED_EMBAUCH] [datetime] NOT NULL,
  [DATE_FIN_DE_CONTRAT] [datetime] NOT NULL,
  CONSTRAINT [PK_CONTRAT] PRIMARY KEY CLUSTERED ([NUMCONTRAT])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTRAT]
  ADD CONSTRAINT [FK_CONTRAT_SALARIE] FOREIGN KEY ([MATRICULE]) REFERENCES [dbo].[SALARIE] ([MATRICULE])
GO