CREATE TABLE [dbo].[INDEMNITES] (
  [CODE_IDM] [char](32) NOT NULL,
  [LIBELLE_IDM] [text] NOT NULL,
  [GAINS_IDM] [money] NOT NULL,
  CONSTRAINT [PK_INDEMNITES] PRIMARY KEY CLUSTERED ([CODE_IDM])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO