CREATE TABLE [dbo].[AVANCE] (
  [CODE_AVC] [char](32) NOT NULL,
  [MATRICULE] [smallint] NOT NULL,
  [DATE_AVC] [datetime] NOT NULL,
  [AVANCE] [money] NOT NULL,
  CONSTRAINT [PK_AVANCE] PRIMARY KEY CLUSTERED ([CODE_AVC])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[AVANCE]
  ADD CONSTRAINT [FK_AVANCE_SALARIE] FOREIGN KEY ([MATRICULE]) REFERENCES [dbo].[SALARIE] ([MATRICULE])
GO