CREATE TABLE [dbo].[HEURES_SUPPLEMENTAIRE] (
  [N_HEURE_SUPP] [smallint] NOT NULL,
  [MATRICULE] [smallint] NOT NULL,
  [TYPE_HEURE_SUPP] [text] NOT NULL,
  [DATE_HEURE_SUPP] [datetime] NOT NULL,
  [NBR_HEURE_SUPP] [smallint] NOT NULL,
  CONSTRAINT [PK_HEURES_SUPPLEMENTAIRE] PRIMARY KEY CLUSTERED ([N_HEURE_SUPP])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[HEURES_SUPPLEMENTAIRE]
  ADD CONSTRAINT [FK_HEURES_SUPPLEMENTAIRE_SALARIE] FOREIGN KEY ([MATRICULE]) REFERENCES [dbo].[SALARIE] ([MATRICULE])
GO