CREATE TABLE [dbo].[COTISATION_FISCALE] (
  [CODE_COT_FIS] [char](32) NOT NULL,
  [LIBELLE_COT_FIS] [text] NOT NULL,
  [IR_NET] [money] NOT NULL,
  [RETENUS_COT_FIS] [money] NOT NULL,
  CONSTRAINT [PK_COTISATION_FISCALE] PRIMARY KEY CLUSTERED ([CODE_COT_FIS])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO